INSERT INTO bh.CUSTOMER(FIRST_NAME, LAST_NAME, CREATED_DTTM) VALUES('Anshul','Luthra',CURRENT_TIMESTAMP );
INSERT INTO bh.CUSTOMER(FIRST_NAME, LAST_NAME, CREATED_DTTM) VALUES('Daan','Smits',CURRENT_TIMESTAMP );
